#!/usr/bin/env bash

SRC="examples/${2}.asm"
OBJ="examples/${2}.o"

case "$1" in
    nasm)
        nasm -f elf64 -O0 $SRC -o nasm.o
        ld nasm.o -o nasm.a
        ./nasm.a
        echo $?
        ;;
    basm)
        #cabal build
        #dist/build/basm/basm $SRC
        ghc Main.hs #-prof -fprof-auto -fprof-cafs
        ./Main $SRC -v #+RTS -xc
        mv $OBJ basm.o

        ld basm.o -o basm.a
        ./basm.a
        echo $?
        ;;
    debug)
        cat $SRC | cabal run | hexdump -C
        ;;
esac
